import Foundation

/// Native canonical PLAN evaluator.  The dynamic result deliberately follows
/// Python's `fedbpp.evaluate_plan` document so it can be compared directly in
/// cross-language fixtures and used as the generation/adaptation gate.
public func evaluatePlan(
  _ planValue: JSONValue,
  database: FEDatabase,
  profile: JSONValue? = nil,
  target: JSONValue? = nil,
  relationships: ExerciseRelationships? = nil
) -> JSONValue {
  let plan = object(planValue), profileObject = profile.map(object), targetObject = target.map(object)
  let cycleDays = int(object(plan["cycle"])["lengthDays"]) ?? 7
  let credits = database.setCredits
  var direct = [String: Double](), indirect = [String: Double](), stabilizer = [String: Double](), patterns = [String: Double]()
  var muscleSessions = [String: Set<String>](), patternSessions = [String: Set<String>]()
  var planned = 0.0, mapped = 0.0, unmapped = 0.0, ineligible = 0.0
  var unmappedRx = [String](), ineligibleRx = [String]()
  for sessionValue in array(plan["sessions"]) {
    let session = object(sessionValue), sid = string(session["planSessionId"]) ?? ""
    for rxValue in array(session["exercises"]) {
      let rx = object(rxValue), count = plannedSetCount(rx); planned += count
      guard let id = string(rx["exerciseId"]), let exercise = try? database.getExercise(id) else { unmapped += count; if let id = string(rx["prescriptionId"]) { unmappedRx.append(id) }; continue }
      mapped += count
      guard exercise.annotation.volumeEligible else { ineligible += count; if let id = string(rx["prescriptionId"]) { ineligibleRx.append(id) }; continue }
      for muscle in exercise.annotation.direct { add(&direct, muscle, count); muscleSessions[muscle, default: []].insert(sid) }
      for muscle in exercise.annotation.indirect { add(&indirect, muscle, count); muscleSessions[muscle, default: []].insert(sid) }
      for muscle in exercise.annotation.stabilizers { add(&stabilizer, muscle, count) }
      for pattern in exercise.annotation.patterns { add(&patterns, pattern, count); patternSessions[pattern, default: []].insert(sid) }
    }
  }
  let effective = Dictionary(uniqueKeysWithValues: Set(direct.keys).union(indirect.keys).union(stabilizer.keys).sorted().map { muscle in (muscle, clean((direct[muscle] ?? 0) * credits.direct + (indirect[muscle] ?? 0) * credits.indirect + (stabilizer[muscle] ?? 0) * credits.stabilizer)) })
  let periodDays = number(targetObject?["periodDays"]) ?? Double(cycleDays), targetScale = periodDays / Double(cycleDays)
  let configuredMuscles = object(targetObject?["muscles"]), muscleRows = Dictionary(uniqueKeysWithValues: Set(configuredMuscles.keys).union(effective.keys).sorted().map { muscle -> (String, JSONValue) in
    let r = targetRange(configuredMuscles[muscle]), actual = clean((effective[muscle] ?? 0) * targetScale)
    let row: [String: JSONValue] = ["actualEffectiveSets": .number(actual), "minimum": nullable(r.min), "target": nullable(r.target), "maximum": nullable(r.max), "min": nullable(r.min), "max": nullable(r.max), "differenceFromTarget": nullable(r.target.map { clean(actual - $0) }), "planEffectiveSetRange": .object(["min": .number(actual), "target": .number(actual), "max": .number(actual)]), "state": .string(configuredMuscles[muscle] == nil ? "not_targeted" : rangeState(actual, r)), "periodDays": .number(periodDays)]
    return (muscle, .object(row))
  })
  let frequencyRows = Dictionary(uniqueKeysWithValues: object(object(targetObject?["frequency"])["muscles"]).keys.sorted().map { muscle -> (String, JSONValue) in
    let r = targetRange(object(object(targetObject?["frequency"])["muscles"])[muscle]), actual = clean(Double(muscleSessions[muscle]?.count ?? 0) * 7 / Double(cycleDays))
    return (muscle, .object(["plannedExposuresPerNativeCycle": .number(Double(muscleSessions[muscle]?.count ?? 0)), "normalizedExposuresPer7Days": .number(actual), "minimum": nullable(r.min), "target": nullable(r.target), "maximum": nullable(r.max), "state": .string(rangeState(actual, r))]))
  })
  let patternRows = Dictionary(uniqueKeysWithValues: object(targetObject?["movementPatterns"]).keys.sorted().map { pattern -> (String, JSONValue) in
    let r = targetRange(object(targetObject?["movementPatterns"])[pattern]), actual = patterns[pattern] ?? 0
    return (pattern, .object(["plannedSets": .number(actual), "minimum": nullable(r.min), "target": nullable(r.target), "maximum": nullable(r.max), "state": .string(rangeState(actual, r))]))
  })
  var familyCounts = [String: Double](); if let relationships { for sessionValue in array(plan["sessions"]) { for rxValue in array(object(sessionValue)["exercises"]) { let rx = object(rxValue); if let id = string(rx["exerciseId"]), let family = relationships.family(for: id)?.familyId { add(&familyCounts, family, plannedSetCount(rx)) } } } }
  let familyRows = Dictionary(uniqueKeysWithValues: object(targetObject?["families"]).keys.sorted().map { family -> (String, JSONValue) in let r = targetRange(object(targetObject?["families"])[family]), actual = familyCounts[family] ?? 0; return (family, .object(["plannedSets": .number(actual), "minimum": nullable(r.min), "target": nullable(r.target), "maximum": nullable(r.max), "state": .string(rangeState(actual, r))])) })
  var hard = [[String: JSONValue]](), soft = [[String: JSONValue]](), supported = Set<String>(), unsupported = [[String: JSONValue]](), unknown = [[String: JSONValue]]()
  let availability = object(profileObject?["availability"]), preferences = object(profileObject?["exercisePreferences"]), constraints = object(profileObject?["constraints"])
  let excludedDays = Set(array(availability["excludedDayOffsets"]).compactMap { int($0) }), excludedExercises = Set(array(constraints["excludedExerciseIds"]).compactMap(string)), excludedFamilies = Set(array(constraints["excludedFamilyIds"]).compactMap(string)), preferredExercises = Set(array(preferences["preferredExerciseIds"]).compactMap(string)), avoidedExercises = Set(array(preferences["avoidedExerciseIds"]).compactMap(string)), preferredFamilies = Set(array(preferences["preferredFamilyIds"]).compactMap(string)), avoidedFamilies = Set(array(preferences["avoidedFamilyIds"]).compactMap(string)), availableEquipment = Set(array(profileObject?["equipment"]).compactMap(string)), body = Set(["body only", "bodyweight", "no equipment", "none"])
  for sessionValue in array(plan["sessions"]) { let session = object(sessionValue), sid = string(session["planSessionId"]) ?? ""; if let day = int(session["dayOffset"]), excludedDays.contains(day) { hard.append(finding("excluded_day_offset", ["sessionId": .string(sid), "dayOffset": .number(Double(day))])) }; for rxValue in array(session["exercises"]) { let rx = object(rxValue); guard let id = string(rx["exerciseId"]) else { continue }; let pid = string(rx["prescriptionId"]) ?? "", family = relationships?.family(for: id)?.familyId
    if excludedExercises.contains(id) { hard.append(finding("excluded_exercise", ["exerciseId": .string(id), "prescriptionId": .string(pid), "sessionId": .string(sid)])) }; if let family, excludedFamilies.contains(family) { hard.append(finding("excluded_family", ["exerciseId": .string(id), "familyId": .string(family), "prescriptionId": .string(pid), "sessionId": .string(sid)])) }
    if preferredExercises.contains(id) { soft.append(finding("preferred_exercise_used", ["exerciseId": .string(id), "prescriptionId": .string(pid), "sessionId": .string(sid)])) }; if avoidedExercises.contains(id) { soft.append(finding("avoided_exercise_used", ["exerciseId": .string(id), "prescriptionId": .string(pid), "sessionId": .string(sid)])) }; if let family, preferredFamilies.contains(family) { soft.append(finding("preferred_family_used", ["exerciseId": .string(id), "familyId": .string(family), "prescriptionId": .string(pid), "sessionId": .string(sid)])) }; if let family, avoidedFamilies.contains(family) { soft.append(finding("avoided_family_used", ["exerciseId": .string(id), "familyId": .string(family), "prescriptionId": .string(pid), "sessionId": .string(sid)])) }
    guard let exercise = try? database.getExercise(id) else { unknown.append(finding("unknown_exercise", ["exerciseId": .string(id), "prescriptionId": .string(pid), "sessionId": .string(sid)])); continue }; let equipment = string(exercise.source?["equipment"])
    if equipment == nil || equipment == "None" || equipment == "other" { unknown.append(finding("unknown_equipment", ["exerciseId": .string(id), "equipment": exercise.source?["equipment"] ?? .null, "prescriptionId": .string(pid), "sessionId": .string(sid)])) } else if body.contains(equipment!) && !availableEquipment.intersection(body).isEmpty || availableEquipment.contains(equipment!) { supported.insert(id) } else { let row = finding("unsupported_equipment", ["equipment": .string(equipment!), "exerciseId": .string(id), "prescriptionId": .string(pid), "sessionId": .string(sid)]); unsupported.append(row); hard.append(row) }
  } }
  let exerciseRange = targetRange(availability["exercisesPerSession"]); var exerciseCounts = [String: JSONValue](); if profileObject != nil && [exerciseRange.min, exerciseRange.target, exerciseRange.max].contains(where: { $0 != nil }) { for sessionValue in array(plan["sessions"]) { let session = object(sessionValue), sid = string(session["planSessionId"]) ?? "", n = Double(array(session["exercises"]).count), status = rangeState(n, exerciseRange); exerciseCounts[sid] = .object(["exerciseCount": .number(n), "minimum": nullable(exerciseRange.min), "target": nullable(exerciseRange.target), "maximum": nullable(exerciseRange.max), "state": .string(status)]); if status == "below_minimum" || status == "above_maximum" { hard.append(finding("exercise_count", ["sessionId": .string(sid), "exerciseCount": .number(n), "minimum": nullable(exerciseRange.min), "maximum": nullable(exerciseRange.max)])) } else if exerciseRange.target != nil && n != exerciseRange.target! { soft.append(finding("exercise_count_target_miss", ["sessionId": .string(sid), "exerciseCount": .number(n), "target": nullable(exerciseRange.target)])) } } }
  let sessionRange = targetRange(availability["sessionsPerCycle"]), sessionCount = Double(array(plan["sessions"]).count), availabilityResult: JSONValue = profileObject == nil || availability.isEmpty ? .object(["plannedSessions": .number(sessionCount), "state": .string("not_evaluated")]) : .object(["plannedSessions": .number(sessionCount), "min": nullable(sessionRange.min), "target": nullable(sessionRange.target), "max": nullable(sessionRange.max), "state": .string(rangeState(sessionCount, sessionRange))])
  let targetGaps = [muscleRows, frequencyRows, patternRows, familyRows].reduce(0) { $0 + $1.values.filter { string(object($0)["state"]) == "below_minimum" }.count }, fraction = planned == 0 ? 1 : clean(mapped / planned), completeness: JSONValue = .object(["plannedSets": .number(clean(planned)), "plannedSetRange": scalarRange(planned), "mappedSets": .number(clean(mapped)), "mappedSetRange": scalarRange(mapped), "unmappedSets": .number(clean(unmapped)), "unmappedSetRange": scalarRange(unmapped), "ineligibleSets": .number(clean(ineligible)), "ineligibleSetRange": scalarRange(ineligible), "mappedFraction": .number(fraction), "unmappedPrescriptions": .array(unmappedRx.sorted().map(JSONValue.string)), "ineligiblePrescriptions": .array(ineligibleRx.sorted().map(JSONValue.string))])
  var warnings = Set<String>(); if unmapped != 0 || ineligible != 0 || !unknown.isEmpty { warnings.insert("coverage is incomplete for one or more PLAN exercises") }; if availability["minutesPerSession"] != nil { warnings.insert("duration estimation is not evaluated by duration-estimation-v1 because PLAN rest/transition inputs are not complete") }; if !object(targetObject?["families"]).isEmpty && relationships == nil { warnings.insert("family targets cannot be evaluated because relationship artifact was not provided") }
  hard.sort { findingKey($0) < findingKey($1) }; soft.sort { findingKey($0) < findingKey($1) }; let status = !hard.isEmpty ? "hard_constraint_violation" : fraction < 1 || (!object(targetObject?["families"]).isEmpty && relationships == nil) ? "incomplete_coverage" : targetGaps > 0 ? "valid_with_target_gaps" : "valid"
  return .object(["summary": .object(["hardConstraintViolations": .number(Double(hard.count)), "targetGaps": .number(Double(targetGaps)), "softPreferenceWarnings": .number(Double(soft.count)), "satisfiesHardConstraints": .bool(hard.isEmpty), "meetsTargetMinimums": .bool(targetGaps == 0), "evaluationStatus": .string(status)]), "muscleCoverage": .object(muscleRows), "frequency": .object(frequencyRows), "movementPatterns": .object(patternRows), "families": .object(["coverage": relationships == nil ? .object(["available": .bool(false), "reason": .string("relationship artifact not provided")]) : .object(Dictionary(uniqueKeysWithValues: familyCounts.keys.sorted().map { ($0, JSONValue.object(["familyId": .string($0), "plannedSets": .number(familyCounts[$0] ?? 0)])) })), "targets": .object(familyRows)]), "equipment": .object(["supportedExercises": .array(supported.sorted().map(JSONValue.string)), "unsupportedExercises": .array(unsupported.map(JSONValue.object)), "unknownEquipmentExercises": .array(unknown.map(JSONValue.object))]), "availability": availabilityResult, "exerciseCounts": .object(exerciseCounts), "preferences": .object(["preferredExercisesUsed": .array(soft.filter { string($0["type"]) == "preferred_exercise_used" }.compactMap { $0["exerciseId"] }.map { $0 }.sorted { string($0)! < string($1)! }), "preferredFamiliesUsed": .array(soft.filter { string($0["type"]) == "preferred_family_used" }.compactMap { $0["familyId"] }.sorted { string($0)! < string($1)! }), "avoidedExercisesUsed": .array(soft.filter { string($0["type"]) == "avoided_exercise_used" }.compactMap { $0["exerciseId"] }.sorted { string($0)! < string($1)! }), "avoidedFamiliesUsed": .array(soft.filter { string($0["type"]) == "avoided_family_used" }.compactMap { $0["familyId"] }.sorted { string($0)! < string($1)! }), "findings": .array(soft.map(JSONValue.object))]), "constraints": .object(["violations": .array(hard.map(JSONValue.object))]), "coverageCompleteness": completeness, "warnings": .array(warnings.sorted().map(JSONValue.string)), "provenance": .object(["analysisVersion": .string("0.1.0"), "analysisPolicy": .string("plan-evaluation-v1"), "planSchemaVersion": plan["schemaVersion"] ?? .null, "profileSchemaVersion": profileObject?["schemaVersion"] ?? .null, "targetSchemaVersion": targetObject?["schemaVersion"] ?? .null, "relationshipSchemaVersion": relationships.map { .string($0.schemaVersion) } ?? .null, "dbSchemaVersion": database.metadata["schemaVersion"] ?? .null, "dbConverterVersion": database.metadata["converterVersion"] ?? .null, "dbUpstreamSha256": object(database.metadata["upstream"])["sha256"] ?? .null, "setCredits": .object(["direct": .number(credits.direct), "indirect": .number(credits.indirect), "stabilizer": .number(credits.stabilizer)]), "durationPolicy": availability["minutesPerSession"] == nil ? .null : .string("duration-estimation-v1")])])
}

private struct EvaluationRange { let min: Double?; let target: Double?; let max: Double? }
private func object(_ value: JSONValue?) -> [String: JSONValue] { guard case .object(let value)? = value else { return [:] }; return value }
private func array(_ value: JSONValue?) -> [JSONValue] { guard case .array(let value)? = value else { return [] }; return value }
private func string(_ value: JSONValue?) -> String? { guard case .string(let value)? = value else { return nil }; return value }
private func number(_ value: JSONValue?) -> Double? { guard case .number(let value)? = value else { return nil }; return value }
private func int(_ value: JSONValue?) -> Int? { number(value).map(Int.init) }
private func nullable(_ value: Double?) -> JSONValue { value.map(JSONValue.number) ?? .null }
private func clean(_ value: Double) -> Double { (value * 1_000_000).rounded() / 1_000_000 }
private func add(_ map: inout [String: Double], _ key: String, _ value: Double) { map[key] = clean((map[key] ?? 0) + value) }
private func targetRange(_ value: JSONValue?) -> EvaluationRange { let o = object(value); if o.isEmpty { return EvaluationRange(min: nil, target: number(value), max: nil) }; return EvaluationRange(min: number(o["min"]) ?? number(o["minimumSets"]), target: number(o["target"]) ?? number(o["targetSets"]), max: number(o["max"]) ?? number(o["maximumSets"])) }
private func rangeState(_ actual: Double, _ range: EvaluationRange) -> String { if let min = range.min, actual < min { return "below_minimum" }; if let max = range.max, actual > max { return "above_maximum" }; guard let target = range.target else { return "within_range" }; if actual == target { return "at_target" }; return actual < target ? "within_range_below_target" : "within_range_above_target" }
private func plannedSetCount(_ rx: [String: JSONValue]) -> Double { let explicit = array(rx["plannedSets"]); if !explicit.isEmpty { return Double(explicit.count) }; let r = targetRange(rx["sets"]); return r.target ?? r.min ?? r.max ?? 0 }
private func scalarRange(_ value: Double) -> JSONValue { .object(["min": .number(clean(value)), "target": .number(clean(value)), "max": .number(clean(value))]) }
private func finding(_ type: String, _ values: [String: JSONValue]) -> [String: JSONValue] { var result = values; result["type"] = .string(type); return result }
private func findingKey(_ value: [String: JSONValue]) -> String { "\(string(value["type"]) ?? ""):\(string(value["exerciseId"]) ?? string(value["familyId"]) ?? string(value["sessionId"]) ?? ""):\(string(value["sessionId"]) ?? ""):\(string(value["prescriptionId"]) ?? "")" }
