pkg <- file.path("R", "fedbpp.R")
source(pkg)
root <- normalizePath(file.path("..", "..", ".."), mustWork = TRUE)
db <- load_database(file.path(root, "free-exercise-db-plusplus.json"))
stopifnot(length(db$exercises) > 800L)
stopifnot(db$exercises[["Bench_Dips"]]$exerciseId == "Bench_Dips")
w <- list(schemaVersion = "0.2.0", sessionId = "r-test", startTime = "2026-01-01T00:00:00Z", exercises = list(list(exerciseId = "Bench_Dips", order = 1L, sets = list(list(setNumber = 1L, setType = "working", completed = TRUE)))))
validate_workout(w)
totals <- effective_sets(w, db)
stopifnot(nrow(totals) > 0L, all(totals$effective_sets >= 0))
stopifnot(nrow(longitudinal_volume(list(w), db)) > 0L)
cat("R consumer package valid\n")
