pkg <- file.path("R", "fedbpp.R")
if (file.exists(pkg)) source(pkg) else library(fedbpp)
root <- normalizePath(file.path("..", "..", ".."), mustWork = TRUE)
if (!file.exists(file.path(root, "free-exercise-db-plusplus.json"))) {
  cat("R package check: repository consumer fixtures unavailable; package load passed\n")
  quit(save = "no", status = 0)
}
db <- load_database(file.path(root, "free-exercise-db-plusplus.json"))
stopifnot(length(db$exercises) > 800L)
stopifnot(db$exercises[["Bench_Dips"]]$exerciseId == "Bench_Dips")
w <- list(schemaVersion = "0.2.0", sessionId = "r-test", startTime = "2026-01-01T00:00:00Z", exercises = list(list(exerciseId = "Bench_Dips", order = 1L, sets = list(list(setNumber = 1L, setType = "working", completed = TRUE)))))
validate_workout(w)
totals <- effective_sets(w, db)
stopifnot(nrow(totals) > 0L, all(totals$effective_sets >= 0))
stopifnot(nrow(longitudinal_volume(list(w), db)) > 0L)
relationships <- load_relationships(file.path(root, "exercise-relationships.json"))
stopifnot(family_for(relationships, "Dumbbell_Bench_Press")$familyId == "bench_press")
stopifnot("Barbell_Bench_Press_-_Medium_Grip" %in% family_members(relationships, "bench_press"))
intent <- read_workout_intent(file.path(root, "fixtures/cross-language/intent/flagship-5day-hypertrophy/input.json"))
resolution <- resolve_intent(intent, db = db)
stopifnot(resolution$status == "resolved_with_defaults")
stopifnot(resolution$environmentPolicy == "commercial-gym-general-v1")
stopifnot(all(resolution$resolvedProfile$availability$preferredDayOffsets == c(0, 1, 2, 3, 5)))
stopifnot(identical(resolution$explicitOverrides$equipmentAdded, character()))
bad <- intent; bad$requestedGoalPolicy <- "general-strength-v1"
stopifnot(resolve_intent(bad, db = db)$conflicts[[1]]$code == "GOAL_POLICY_MISMATCH")
cat("R consumer package valid\n")
