package com.fedbpp

import kotlinx.serialization.json.*

private fun JsonElement?.co() = this as? JsonObject ?: JsonObject(emptyMap())
private fun JsonElement?.ca() = this as? JsonArray ?: JsonArray(emptyList())
private fun JsonElement?.cs() = (this as? JsonPrimitive)?.contentOrNull
private fun JsonElement?.cn() = (this as? JsonPrimitive)?.doubleOrNull
private fun policyJson(id: String) = buildJsonObject {
    put("policyId", id); put("policyVersion", "1.0.0"); put("description", "Conservative deterministic advisory adaptation. Ambiguous evidence holds the PLAN."); put("decisionPriority", buildJsonArray { listOf("hard_constraints", "structural_invalidity", "target_minimums", "adherence", "repeated_failure", "progression", "target_optimization", "preferences", "continuity", "stable_tie_break").forEach(::add) })
    put("stateWindowPolicy", "last_28_days"); put("exerciseProgressionPolicy", "double-progression-v1"); put("adherencePolicy", "quantitative-adherence-v1"); put("volumeAdjustmentPolicy", "effective-set-one-step-v1"); put("frequencyAdjustmentPolicy", "canonical-exposure-v1"); put("substitutionPolicy", "explicit-substitution-v1"); put("regenerationPolicy", "v1.8-generator-v1")
    put("parameters", buildJsonObject { put("minimumRecentPerformances", 2); put("repeatedFailureThreshold", 2); put("repeatedSkipThreshold", 2); put("repeatedSubstitutionThreshold", 2); put("maxSetsAddedPerMusclePerRevision", 1); put("maxSetsRemovedPerMusclePerRevision", 1); put("maxTotalSetChangesPerRevision", 2); put("loadIncrement", buildJsonObject { put("value", 2.5); put("unit", "kg") }) })
}
private fun decisionId(type: String, pid: String) = "decision-$type-$pid"
private fun excesses(evaluation: JsonElement): Map<String, Double> {
    val result = sortedMapOf<String, Double>(); val root = evaluation.co()
    fun read(section: JsonObject) { section.forEach { (k, v) -> val x = v.co(); val actual = x["actualEffectiveSets"].cn() ?: x["normalizedExposuresPer7Days"].cn() ?: x["plannedSets"].cn() ?: 0.0; val max = x["maximum"].cn(); if (max != null && actual > max) result[k] = actual - max } }
    read(root["muscleCoverage"].co()); read(root["frequency"].co()); read(root["movementPatterns"].co()); read(root["families"].co()["targets"].co()); return result
}
private fun issue(code: String) = buildJsonObject { put("code", code) }

fun adaptPlanCanonical(request: PlanAdaptationRequest, database: Database, relationships: ExerciseRelationships?): JsonElement {
    val profile = apiJson.encodeToJsonElement(TrainingProfile.serializer(), request.profile); val target = apiJson.encodeToJsonElement(VolumeTarget.serializer(), request.target); val current = request.currentPlan.toJson()
    val currentEval = evaluatePlan(current, database, profile, target, relationships); val state = when {
        request.trainingState != null -> apiJson.encodeToJsonElement(TrainingState.serializer(), request.trainingState)
        request.history != null && request.asOf != null -> deriveTrainingStateCanonical(apiJson.encodeToJsonElement(TrainingHistory.serializer(), request.history), request.asOf, TrainingHistoryWindow.Last28Days, database, relationships, target)
        else -> JsonNull
    }
    if (state is JsonNull) return buildJsonObject { put("status", "insufficient_data"); put("currentPlan", current); put("proposedPlan", JsonNull); put("currentEvaluation", currentEval); put("proposedEvaluation", JsonNull); put("trainingState", JsonNull); put("decisions", buildJsonArray { }); put("changes", buildJsonArray { }); put("unresolvedIssues", buildJsonArray { add(issue("INSUFFICIENT_HISTORY")) }); put("policy", policyJson(request.policy)); put("provenance", buildJsonObject { put("coachingVersion", "1.9.0"); put("coachingPolicyId", request.policy) }) }
    val stateObject = state.co(); val proposedRevision = current["revisionId"].cs()?.let { if (it.startsWith("r") && it.drop(1).toIntOrNull() != null) "r${it.drop(1).toInt() + 1}" else "$it-adaptive-1" } ?: "r2"
    if (currentEval.co()["summary"].co()["satisfiesHardConstraints"]?.jsonPrimitive?.booleanOrNull != true) {
        val generated = generatePlan(profile, target, database, relationships, emptyList(), buildJsonObject { put("currentPlan", current); put("trainingState", state); put("planId", current["planId"] ?: JsonPrimitive("generated-plan")); put("revisionId", JsonPrimitive(proposedRevision)); put("name", current["name"] ?: JsonPrimitive("Generated full-body-general-v1")) })
        if (generated.co()["plan"] !is JsonNull && generated.co()["plan"] != null) {
            val d = buildJsonObject { put("schemaVersion", "0.1.0"); put("decisionId", "decision-regenerate"); put("decisionType", "regenerate_plan"); put("policyId", request.policy); put("policyVersion", "1.0.0"); put("planId", current["planId"] ?: JsonNull); put("revisionId", current["revisionId"] ?: JsonNull); put("prescriptionId", JsonNull); put("exerciseId", JsonNull); put("before", buildJsonObject { }); put("after", buildJsonObject { }); put("reasonCodes", buildJsonArray { add("PLAN_REGENERATION_REQUIRED") }); put("evidence", currentEval.co()["constraints"] ?: buildJsonObject { }); put("provenance", stateObject["provenance"] ?: buildJsonObject { }) }
            val c = buildJsonObject { put("type", "PLAN_REGENERATED"); put("reasonCodes", buildJsonArray { add("PLAN_REGENERATION_REQUIRED") }); put("decisionIds", buildJsonArray { add("decision-regenerate") }) }
            return buildJsonObject { put("status", "regeneration_proposed"); put("currentPlan", current); put("proposedPlan", generated.co()["plan"] ?: JsonNull); put("currentEvaluation", currentEval); put("proposedEvaluation", generated.co()["evaluation"] ?: JsonNull); put("trainingState", state); put("decisions", buildJsonArray { add(d) }); put("changes", buildJsonArray { add(c) }); put("unresolvedIssues", buildJsonArray { }); put("policy", policyJson(request.policy)); put("provenance", buildJsonObject { put("coachingVersion", "1.9.0"); put("coachingPolicyId", request.policy); put("coachingPolicyVersion", "1.0.0"); put("planningPolicyId", request.planningPolicy?.let(::JsonPrimitive) ?: JsonPrimitive("full-body-general-v1")); put("trainingStateVersion", stateObject["stateVersion"] ?: JsonNull); put("historyWindow", stateObject["historyWindow"] ?: JsonNull); put("stateProvenance", stateObject["provenance"] ?: JsonNull); put("dbSchemaVersion", database.metadata["schemaVersion"] ?: JsonNull); put("dbConverterVersion", database.metadata["converterVersion"] ?: JsonNull); put("dbUpstreamSha256", (database.metadata["upstream"] as? JsonObject)?.get("sha256") ?: JsonNull); put("setCredits", database.metadata["setCredits"] ?: JsonNull); put("evaluationVersion", "0.1.0") }) }
        }
    }
    val sessions = current["sessions"].ca().map { it.jsonObject }.toMutableList(); val decisions = mutableListOf<JsonElement>(); val changes = mutableListOf<JsonElement>(); val states = stateObject["exerciseState"].co(); val adh = stateObject["adherenceState"].co(); val substitutions = adh["substitutionHistoryByPrescription"].co(); val skipped = adh["skippedPrescriptionCounts"].co()
    for (si in sessions.indices) {
        val exercises = sessions[si]["exercises"].ca().map { it.jsonObject }.toMutableList()
        for (ei in exercises.indices) {
            var rx = exercises[ei]; val id = rx["exerciseId"].cs() ?: continue; val pid = rx["prescriptionId"].cs() ?: continue
            if ((skipped[pid].cn() ?: 0.0) >= 2.0) decisions += buildJsonObject { put("schemaVersion", "0.1.0"); put("decisionId", "decision-hold-$pid"); put("decisionType", "hold"); put("policyId", request.policy); put("policyVersion", "1.0.0"); put("planId", current["planId"] ?: JsonNull); put("revisionId", current["revisionId"] ?: JsonNull); put("prescriptionId", pid); put("exerciseId", id); put("before", buildJsonObject { }); put("after", buildJsonObject { }); put("reasonCodes", buildJsonArray { add("REPEATEDLY_SKIPPED") }); put("evidence", buildJsonObject { put("skippedPrescriptionCount", skipped[pid] ?: JsonNull) }); put("provenance", stateObject["provenance"] ?: buildJsonObject { }) }
            val substitutionRoot = substitutions[pid].co(); val substitutionEntry = substitutionRoot.entries.sortedBy { it.key }.firstOrNull(); val sub = substitutionEntry?.value.co(); if ((sub["count"].cn() ?: 0.0) >= 2.0) {
                val replacement = substitutionEntry?.key; val ex = replacement?.let { runCatching { database.getExercise(it) }.getOrNull() }
                if (ex != null && ex.annotation.volumeEligible) {
                    val before = rx; val updated = rx.toMutableMap(); updated["exerciseId"] = replacement.let(::JsonPrimitive); ex.source["name"]?.let { updated["exerciseName"] = it }; rx = JsonObject(updated); exercises[ei] = rx
                    val did = decisionId("substitute_exercise", pid); val evidence = buildJsonObject { put("prescriptionId", pid); put("replacementExerciseId", replacement); put("substitutionCount", sub["count"] ?: JsonPrimitive(0)); put("sessionIds", sub["sessionIds"] ?: JsonArray(emptyList())); put("timestamps", sub["timestamps"] ?: JsonArray(emptyList())) }; decisions += buildJsonObject { put("schemaVersion", "0.1.0"); put("decisionId", did); put("decisionType", "substitute_exercise"); put("policyId", request.policy); put("policyVersion", "1.0.0"); put("planId", current["planId"] ?: JsonNull); put("revisionId", current["revisionId"] ?: JsonNull); put("prescriptionId", pid); put("exerciseId", id); put("before", buildJsonObject { put("exerciseId", id) }); put("after", buildJsonObject { put("exerciseId", replacement) }); put("reasonCodes", buildJsonArray { add("REPEATED_SUBSTITUTION") }); put("evidence", evidence); put("provenance", stateObject["provenance"] ?: buildJsonObject { }) }
                    changes += buildJsonObject { put("type", "EXERCISE_SUBSTITUTED"); put("prescriptionId", pid); put("exerciseId", id); put("before", before); put("after", rx); put("reasonCodes", buildJsonArray { add("REPEATED_SUBSTITUTION") }); put("decisionIds", buildJsonArray { add(did) }) }
                }
            }
            val progressionExerciseId = rx["exerciseId"].cs() ?: id; val progression = applyProgressionPolicy("double-progression-v1", rx, states[progressionExerciseId] ?: states[id] ?: buildJsonObject { }, policyJson(request.policy)["parameters"]).co(); val type = progression["decisionType"].cs(); val did = type?.let { decisionId(it, pid) }; if (did != null) { val d = progression.toMutableMap(); d["decisionId"] = did.let(::JsonPrimitive); d["planId"] = current["planId"] ?: JsonNull; d["revisionId"] = current["revisionId"] ?: JsonNull; d["provenance"] = stateObject["provenance"] ?: buildJsonObject { }; decisions += JsonObject(d); if (type == "increase_load") { val before = rx; val updated = rx.toMutableMap(); updated["load"] = progression["after"].co()["load"] ?: rx["load"]!!; rx = JsonObject(updated); exercises[ei] = rx; changes += buildJsonObject { put("type", "LOAD_CHANGED"); put("prescriptionId", pid); put("exerciseId", progressionExerciseId); put("before", before); put("after", rx); put("reasonCodes", buildJsonArray { add("PROGRESSION_CRITERIA_MET") }); put("decisionIds", buildJsonArray { add(did) }) } } }
        }
        sessions[si] = JsonObject(sessions[si].toMutableMap().apply { put("exercises", JsonArray(exercises)) })
    }
    val proposed = JsonObject(current.toMutableMap().apply { put("sessions", JsonArray(sessions)); if (changes.isNotEmpty()) put("revisionId", JsonPrimitive(proposedRevision)) }); val proposedEval = if (changes.isEmpty()) null else evaluatePlan(proposed, database, profile, target, relationships); val rejected = proposedEval != null && (proposedEval.co()["summary"].co()["satisfiesHardConstraints"]?.jsonPrimitive?.booleanOrNull != true || excesses(proposedEval).any { (k, v) -> v > (excesses(currentEval)[k] ?: 0.0) })
    val orderedDecisions = decisions.sortedWith(compareBy({ it.co()["prescriptionId"].cs() ?: "" }, { it.co()["decisionType"].cs() ?: "" }, { it.co()["decisionId"].cs() ?: "" })); val orderedChanges = changes.sortedWith(compareBy({ it.co()["prescriptionId"].cs() ?: "" }, { it.co()["type"].cs() ?: "" }))
    return buildJsonObject { put("status", if (rejected) "unsatisfiable" else if (changes.isNotEmpty()) "revision_proposed" else if (orderedDecisions.isEmpty()) "insufficient_data" else "no_change"); put("currentPlan", current); put("proposedPlan", if (!rejected && changes.isNotEmpty()) proposed else JsonNull); put("currentEvaluation", currentEval); put("proposedEvaluation", proposedEval ?: JsonNull); put("trainingState", state); put("decisions", JsonArray(orderedDecisions)); put("changes", JsonArray(orderedChanges)); put("unresolvedIssues", buildJsonArray { if (rejected) add(issue("EVALUATOR_GATE_REJECTED")) }); put("policy", policyJson(request.policy)); put("provenance", buildJsonObject { put("coachingVersion", "1.9.0"); put("coachingPolicyId", request.policy); put("coachingPolicyVersion", "1.0.0"); put("planningPolicyId", request.planningPolicy?.let(::JsonPrimitive) ?: JsonNull); put("trainingStateVersion", stateObject["stateVersion"] ?: JsonNull); put("historyWindow", stateObject["historyWindow"] ?: JsonNull); put("stateProvenance", stateObject["provenance"] ?: JsonNull); put("dbSchemaVersion", database.metadata["schemaVersion"] ?: JsonNull); put("dbConverterVersion", database.metadata["converterVersion"] ?: JsonNull); put("dbUpstreamSha256", (database.metadata["upstream"] as? JsonObject)?.get("sha256") ?: JsonNull); put("setCredits", database.metadata["setCredits"] ?: JsonNull); put("evaluationVersion", "0.1.0") }) }
}
